autobot/urls.py
from django.contrib import admin
from django.urls import path, reverse
from django.conf.urls import include
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='btcbot:index')),
    path('btcbot/', include('btcbot.urls')),
    path('profiles/', include('profiles.urls')),
]

admin.site.site_header = 'AutoBot Administration'

admin.site.site_header = 'LocalBitcoins_bot Administration'

btcbot/urls.py
from django.urls import path
from django.contrib.auth import views
from django.views import generic
from .views import IndexView, MessageView, SettingsView, EditorView


app_name = 'btcbot'
urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    path('messages/<pk>', MessageView.as_view(), name='message'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('editor/', EditorView.as_view(), name='editor'),
]

btcbot/models.py
from django.db import models


class BotSetting(models.Model):
    name = models.CharField(max_length=64, unique=True)
    api_key_qiwi = models.ManyToManyField('profiles.APIKeyQiwi', blank=True)
    buy_ad_settings = models.ForeignKey('btcbot.AdSetting',
                                        on_delete=models.CASCADE,
                                        related_name='buy_ad')
    sell_ad_settings = models.ForeignKey('btcbot.AdSetting',
                                         on_delete=models.CASCADE,
                                         related_name='sell_ad')
    telegram_bot_settings = models.ForeignKey('profiles.TelegramBotSettings', on_delete=models.CASCADE,
                                               blank=True,
                                               null=True)
    target_profit = models.IntegerField()
    qiwi_profit_fee = models.DecimalField(max_digits=2, decimal_places=1, default='1.8')
    volume_max = models.IntegerField(null=True)
    volume_min = models.IntegerField(null=True)
    switch_buy_ad_upd = models.BooleanField(default=False)
    switch_sell_ad_upd = models.BooleanField(default=False)
    switch_bot_buy = models.BooleanField(default=False)
    switch_bot_sell = models.BooleanField(default=False)
    switch_rev_send_sell = models.BooleanField(default=False)
    switch_rev_send_buy = models.BooleanField(default=False)
    switch_profit_fixator = models.BooleanField(default=True)
    all_wallets_blocked = models.BooleanField(default=False)
    is_ad_visible = models.BooleanField(default=False)
    qiwi_limit = models.IntegerField(default=50000)
    greetings_text = models.TextField(blank=True, null=True)
    farewell_text = models.TextField(blank=True, null=True)
    review_text = models.TextField(blank=True, null=True)

    def __str__(self):
        return '%s' % self.name

class AdSetting(models.Model):
    name = models.CharField(max_length=64, unique=True)
    ad_id = models.IntegerField(unique=True)
    trade_direction = models.CharField(max_length=64,
                                       choices=(('buy-bitcoins-online',
                                                 'ONLINE_SELL'),
                                                ('sell-bitcoins-online',
                                                 'ONLINE_BUY')
                                                ))
    payment_method = models.CharField(
                                max_length=64,
                                choices=(('qiwi', 'QIWI'),
                                         ('cash-deposit', 'CASH_DEPOSIT'),
                                         ('transfers-with-specific-bank', 'SPECIFIC_BANK'),
                                         ('yandex-money', 'YANDEXMONEY')))
    my_price = models.IntegerField(null=True, blank=True)
    stop_price = models.DecimalField(max_digits=9,
                                     decimal_places=2,
                                     blank=True,
                                     null=True)
    api_key = models.ForeignKey('profiles.APIKey',
                                on_delete=models.CASCADE)
    def __str__(self):
        return '%s' % self.name


class MeanBuyTrades(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    btc_amount = models.DecimalField(max_digits=10, decimal_places=8, null=True)
    price_rub = models.DecimalField(max_digits=9, decimal_places=2)
    is_fee_accounted = models.BooleanField(default=False)
    def __str__(self):
        return 'Buy_active: %s' % str(self.created_at)

class OpenTrades(models.Model):
    trade_id = models.IntegerField()
    contragent = models.CharField(max_length=128)
    is_verified = models.BooleanField(default=False)
    amount_rub = models.DecimalField(max_digits=9,
                                     decimal_places=2)
    amount_btc = models.DecimalField(max_digits=10,
                                     decimal_places=8)
    created_at = models.DateTimeField(auto_now_add=True)
    reference_text = models.CharField(max_length=256)
    api_key_qiwi = models.ForeignKey('profiles.APIKeyQiwi', on_delete=models.CASCADE, blank=True, null=True)
    sent_first_message = models.BooleanField(default=False)
    sent_qiwi = models.BooleanField(default=False)
    marked_paid = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    who_marked_paid = models.ForeignKey('profiles.Profile', on_delete=models.CASCADE, blank=True, null=True)
    sent_second_message = models.BooleanField(default=False)
    disputed = models.BooleanField(default=False)
    def __str__(self):
        return 'Open trade #%d' % self.trade_id

btcbot/views.py
import json
import dateparser
from decimal import *
from django.shortcuts import redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.utils import timezone
from .models import OpenTrades, BotSetting
from profiles.models import Profile
from info_data.models import OperatorsWorkingShift, ReleasedTradesInfo
from btcbot.trader.local_api import LocalBitcoin
from datetime import timedelta
import telegram


class IndexView(LoginRequiredMixin, generic.ListView):
    model = OpenTrades
    template_name = 'btcbot/index.html'
    login_url = '/profiles/login/'

    def get_queryset(self, **kwargs):
        qs = super().get_queryset(**kwargs)
        qs = qs.order_by('-created_at')
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['opened_shift'] = OperatorsWorkingShift.objects.all().order_by('-start_working').first()
        return context

class MessageView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'btcbot/messages.html'
    login_url = '/profiles/login/'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        trade = OpenTrades.objects.get(id=int(context['pk']))
        context['amount_rub'] = trade.amount_rub
        bot = BotSetting.objects.get(name='Bot_QIWI')
        lbtc = LocalBitcoin(bot.sell_ad_settings.api_key.api_key, bot.sell_ad_settings.api_key.api_secret)
        messages = lbtc.get_contact_messages(str(trade.trade_id))
        try:
            messages = messages.json()
        except json.decoder.JSONDecodeError:
            context['json_except'] = True
        if 'json_except' not in context.keys():
            context['trade_messages'] = []
            for i in messages['data']['message_list'][::-1]:
                i['created_at'] = dateparser.parse(i['created_at']).astimezone()
                i['sender']['last_online'] = dateparser.parse(i['sender']['last_online']).astimezone()
                i['is_verified'] = trade.is_verified
                context['trade_messages'].append(i)
        return self.render_to_response(context)

class SettingsView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'btcbot/settings.html'
    login_url = '/profiles/login/'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['bot'] = BotSetting.objects.get(name='Bot_QIWI')
        bot = BotSetting.objects.get(name='Bot_QIWI')
        context['wallets'] = bot.api_key_qiwi.all().order_by('name')
        return self.render_to_response(context)

class EditorView(LoginRequiredMixin, generic.View):
    http_method = ['post']
    login_url = '/profiles/login/'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.bot = BotSetting.objects.get(name='Bot_QIWI')
        self.lbtc = LocalBitcoin(self.bot.sell_ad_settings.api_key.api_key, self.bot.sell_ad_settings.api_key.api_secret)
        self.telegram_bot = telegram.Bot(token=self.bot.telegram_bot_settings.token)

    def post(self, request, *args, **kwargs):
        if request.POST.get('editor') == 'opentrade_paid':
            opentrade_id = int(request.POST.get('opentrade_id'))
            operator = Profile.objects.get(id=request.user.id)
            self._change_opentrade_paid(opentrade_id, operator=operator)
        elif request.POST.get('editor') == 'send_message':
            trade = OpenTrades.objects.get(id=int(request.POST.get('opentrade_id')))
            self.lbtc.post_message_to_contact(str(trade.trade_id), request.POST.get('message'))
            return redirect('btcbot:message', pk=trade.id)
        elif request.POST.get('editor') == 'download_attachment':
            url = request.POST.get('attachment_url').split('/')
            response = self.lbtc.get_trade_attachment(url[5], url[6])
            return HttpResponse(response, content_type=response.headers['Content-Type'])
        elif request.POST.get('editor') == 'switch_bot_sell_ad':
            if self.bot.switch_bot_sell:
                self.bot.switch_bot_sell = False
            else:
                self.bot.switch_bot_sell = True
            self.bot.save()
            return redirect('btcbot:settings')
        elif request.POST.get('editor') == 'change_target_profit':
            self.bot.target_profit = int(request.POST.get('target_profit'))
            self.bot.save()
            return redirect('btcbot:settings')
        elif request.POST.get('editor') == 'open_new_shift':
            OperatorsWorkingShift.objects.create(start_working=timezone.now().astimezone(),
                                                 operator=request.user)
            message = '''Смена оператора {0} открыта
{1}'''.format(request.user.get_username(), timezone.now().astimezone())
            self.telegram_bot.send_message(self.bot.telegram_bot_settings.chat_report, message)
        elif request.POST.get('editor') == 'close_opened_shift':
            shift = OperatorsWorkingShift.objects.get(id=int(request.POST.get('shift_id')))
            self._close_opened_shift(shift, request.user)
        return redirect('btcbot:index')

    def _change_opentrade_paid(self, opentrade_id, operator):
        trade = OpenTrades.objects.get(id=opentrade_id)
        if trade.marked_paid:
            trade.marked_paid = False
        else:
            trade.marked_paid = True
            trade.who_marked_paid = operator
        trade.save()

    def _close_opened_shift(self, shift, operator):
        trades = ReleasedTradesInfo.objects.filter(who_released_btc=operator).filter(created_at__range=[shift.start_working,
                                                                                                        timezone.now()])
        amount_btc, amount_rub, tot_sec, profit, mean_sell_price = Decimal('0.0'), Decimal('0.0'), 0, Decimal('0.0'), Decimal('0.0')
        for trade in trades:
            amount_rub += trade.amount_rub
            amount_btc += trade.amount_btc
            if trade.deal_processed_time:
                tot_sec += trade.deal_processed_time.total_seconds()
            profit += trade.profit_rub_trade
            mean_sell_price += trade.rate_rub

        if not trades:
            mean_deal = timedelta(0)
            mean_sell_price = 0
        else:
            mean_sec = tot_sec / len(trades)
            mean_deal = timedelta(seconds=round(mean_sec, 0))
            mean_sell_price = mean_sell_price / len(trades)

        shift.end_working = timezone.now().astimezone()
        shift.shift_duration = shift.end_working - shift.start_working
        shift.number_of_deals = len(trades)
        shift.amount_sell_btc = amount_btc
        shift.amount_sell_rub = amount_rub
        shift.mean_deal_processing = mean_deal
        shift.profit_rub = profit
        shift.save()
        message = '''Смена оператора {0} закрыта
{1}
        
Длительность смены:
{2}

Среднее время обработки:
{3}

Количество сделок:
{4}
       
Сумма в битках:
{5}

Сумма в рублях:
{6}

Средний курс продажи:
{7}
        
Профит:
{8}        
        '''.format(shift.operator,
                   timezone.now().astimezone(),
                   shift.shift_duration,
                   shift.mean_deal_processing,
                   shift.number_of_deals,
                   shift.amount_sell_btc,
                   shift.amount_sell_rub,
                   mean_sell_price,
                   shift.profit_rub)
        self.telegram_bot.send_message(self.bot.telegram_bot_settings.chat_report, message)

templates/btcbot/index.html
{% extends 'base.html' %}
{% load static %}


{% block meta_block_add %}<meta http-equiv="refresh" content="5">{% endblock %}


{% block title %}Открытые сделки{% endblock %}


{% block nav_baractive_index %}active{% endblock %}


{% block content %}
    <div class="starter-template">

        <h1 class="bold"><b>Открытые сделки</b></h1>

        {% if messages %}
        <div class="alert alert-success" role="alert">
            <ul class="messages ">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
      {% if opened_shift.start_working and opened_shift.end_working %}
        <div class="container">
            <form action="{% url 'btcbot:editor' %}" method="post">
                {% csrf_token %}
                <input type='hidden' name='editor' value='open_new_shift' />
                <button class="btn btn-dark" type="submit" onclick="return confirm('Вы уверены?')"><b>Открыть смену</b></button>
            </form><br />
        </div>
      {% else %}
          <div class="container">
              <form action="{% url 'btcbot:editor' %}" method="post">
                {% csrf_token %}
                <input type='hidden' name='shift_id' value='{{ opened_shift.id }}' />
                <input type='hidden' name='editor' value='close_opened_shift' />
                <button class="btn btn-dark" type="submit" onclick="return confirm('Вы уверены?')"><b>Закрыть смену</b></button>
              </form><br />
          </div>
      {% endif %}
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Номер сделки</th>
            <th scope="col">Верифицирован?</th>
            <th scope="col">Сумма руб.</th>
            <th scope="col">Сумма BTC</th>
            <th scope="col">Дата создания</th>
            <th scope="col">Кошелек</th>
            <th scope="col">Первое сообщение?</th>
            <th scope="col">Пометка об оплате?</th>
            <th scope="col">Деньги пришли?</th>
            <th scope="col">Второе сообщение?</th>
            <th scope="col">Оспаривается?</th>
            <th scope="col">Чат</th>
          </tr>
        </thead>
        <tbody>
            {% for opentrade in opentrades_list %}
            <tr>
              <th scope="row">{{ opentrade.trade_id }}</th>
                <td>{% if opentrade.is_verified %}<b>Да</b>{% else %}Нет{% endif %}</td>
                <td>{{ opentrade.amount_rub|floatformat:2 }}</td>
                <td>{{ opentrade.amount_btc|floatformat:8 }}</td>
                <td>{{ opentrade.created_at }}</td>
                <td>{{ opentrade.api_key_qiwi.name }}<br/>
                    {% if opentrade.api_key_qiwi.is_blocked %}Заблокирован{% endif %}</td>
                <td>{% if opentrade.sent_first_message %}Да {% else %} Нет {% endif %}</td>
                <td>{% if opentrade.sent_qiwi %}
                    <button type="button" class="btn btn-warning"><b>Типа оплачено</b></button>
                    {% else %}
                        Не оплачено
                    {% endif %}
                </td>
                <td>{% if opentrade.marked_paid and not opentrade.disputed %}
                        <form action="{% url 'btcbot:editor' %}" method="post">
                            {% csrf_token %}
                            <input type='hidden' name='opentrade_id' value='{{ opentrade.id }}' />
                            <input type='hidden' name='editor' value='opentrade_paid' />
                            <button class="btn btn-success" type="submit"><b>Да</b></button>
                        </form><br />
                    {% elif not opentrade.marked_paid and not opentrade.disputed %}
                        <form action="{% url 'btcbot:editor' %}" method="post">
                            {% csrf_token %}
                            <input type='hidden' name='opentrade_id' value='{{ opentrade.id }}' />
                            <input type='hidden' name='editor' value='opentrade_paid' />
                            <button class="btn btn-danger" onclick="return confirm('Вы уверены, что деньги пришли?')" type="submit"><b>Нет</b></button>
                        </form><br />
                    {% else %}
                        Оспаривается <br/> Битки нельзя отпустить
                    {% endif %}</td>
                <td>{% if opentrade.sent_second_message %}Да {% else %} Нет {% endif %}</td>
                <td>{% if opentrade.disputed %}Да {% else %} Нет {% endif %}</td>
                <td>{% if not opentrade.disputed %}
                        <button class="btn btn-info" type="button"><b><a style="color: white;" href="{% url 'btcbot:message' opentrade.id %}" target="_blank">Открыть чат</a></b></button>
                    {% else %}
                        <p>Сделка оспаривается. Сообщения недоступны</p>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>

{% endblock %}

templates/btcbot/messages.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Сообщения по сделке {{ opentrade.id }}{% endblock %}


{% block nav_baractive_index %}active{% endblock %}


{% block content %}
    <div class="starter-template">

        <h1 class="bold"><b>Сообщения по сделке {{ opentrade.id }}</b></h1>

        {% if messages %}
        <div class="alert alert-success" role="alert">
            <ul class="messages ">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

      <div class="container">
      {% if not json_except %}
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Дата</th>
            <th scope="col">Отправитель</th>
            <th scope="col">Был онлайн</th>
            <th scope="col">Текст</th>
          </tr>
        </thead>
        <tbody>
            <td></td>
            <td><b>Сумма сделки:<br/><br/>  <p style="color: darkred;">{{ amount_rub }} руб.</p></b></td>
            <td></td>
            <td><form action="{% url 'btcbot:editor' %}" method="post">
                    {% csrf_token %}
                    <input type='hidden' name='opentrade_id' value='{{ pk }}' />
                    <input type='hidden' name='editor' value='send_message' />
                    <textarea rows="5" cols="80" name="message" required placeholder="Сообщение"></textarea>
                    <button class="btn btn-info" type="submit"><b>Отправить</b></button>
                </form><br /></td>
            {% for trade_message in trade_messages %}
            <tr>
                <th scope="row" >{{ trade_message.created_at|date:"Y-m-d H:i:s e" }}</th>
                <td>{% if trade_message.is_admin %}
                        <p style="color: red"><b>Админ</b></p>
                    {% else %}
                        {% if trade_message.sender.username == 'DeluxObmen' %}
                            <p><b>Robin</b></p>
                        {% else %}
                            {% if trade_message.is_verified %}
                                <p style="color:darkblue"><b>Контрагент Верифицирован</b></p>
                            {% else %}
                                <p style="color:darkgreen"><b>Контрагент</b></p>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </td>
                <td>{{ trade_message.sender.last_online|date:"Y-m-d H:i:s e" }}</td>
                <td>{{ trade_message.msg|linebreaksbr }}
                    {% if trade_message.attachment_url %}
                        <form action="{% url 'btcbot:editor' %}" method="post" target="_blank">
                            {% csrf_token %}
                            <input type='hidden' name='attachment_url' value='{{ trade_message.attachment_url }}' />
                            <input type='hidden' name='editor' value='download_attachment' />
                            <button class="btn btn-info btn-sm" type="submit">Прикреплено к сообщению</button>
                        </form><br />
                    {% endif %}
                </td>
            {% endfor %}
        </tbody>
      </table>
      {% else %}
        <h1>Ошибка! Необходимо перезагрузить страницу</h1>
      {% endif %}
      </div>
    </div>

{% endblock %}

templates/btcbot/reports.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Отчеты{% endblock %}


{% block nav_baractive_reports %}active{% endblock %}


{% block content %}
  <div class="starter-template">
    
    <h1 class="bold"><b>Параметры отчета</b></h1>

    {% if messages %}
      <div class="alert alert-success" role="alert">
        <ul class="messages ">
	  {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      </div>
    {% endif %}

    <div class="container">
      <form action="{% url 'ad_bot:reports' %}" method="post">
	{% csrf_token %}
	<select name = "adbot_chooser">
	  {% for i in adbot %}
	    <option value="{{i.id}}">{{ i.name }}</option>
	  {% endfor %}
	</select></br>
	</br><label for="date_1">Дата начала:</label>
	</br><p><input type="datetime-local" name="date_1"></p></br>
	<label for="date_2">Дата окончания:</label>
	<p><input type="datetime-local" name="date_2"></p></br>
	<button class="btn btn-success" type="submit"><b>Сформировать отчет</b></button>
      </form><br />
    </div>
  {% if method == "post" %}
	<p><b>Много раз не нажимать!</b></p>
	<a href={% url 'ad_bot:update' %}><button class="btn btn-danger"><b>Обновить данные вручную</b></button></a>
  {% endif %}

  {% if is_data == "2" %}
    <div class="container">
      <p><b>Средний курс:</b> {{ mean_price|floatformat:2 }}</p>
      <p><b>Cумма в рублях на Qiwi:</b> {{ sum_rub|floatformat:2 }}</p>
      <p><b>Сумма в рублях наличные (-1.8%):</b> {{ sum_rub_qiwi|floatformat:2 }}</p>
      <p><b>Cумма в битках:</b> {{ sum_all_btc|floatformat:8 }}</p>
      <p><b>Количество сделок:</b> {{ number_trades }}</p>

      <br /><div class="row">
        <div class="col border">Номер</div>
        <div class="col border">Дата</div>
        <div class="col border">ID</div>
        <div class="col border">Контрагент</div>
        <div class="col border">Курс</div>
        <div class="col border">Сумма в руб.</div>
        <div class="col border">Сумма в битках</div>
        <div class="col border">Комиссия в битках</div>
      </div>
      {% for i in report_raw %}
        <div class="row">
	  <div class="col border">{{ forloop.counter }}</div>
	  <div class="col border">{{ i.date }}</div>
          <div class="col border">{{ i.contact_id }}</div>
          <div class="col border">{{ i.agent }}</div>
          <div class="col border">{{ i.price|floatformat:2 }}</div>
          <div class="col border">{{ i.amount_rub|floatformat:0 }}</div>
          <div class="col border">{{ i.amount_btc|floatformat:8 }}</div>
          <div class="col border">{{ i.fee_btc|floatformat:8 }}</div>
        </div>
      {% endfor %}   
    </div>
  {% elif is_data == "1" %}
    <p><b>Нет информации по указанному периоду</b></p>
  {% endif %}
  </div>

{% endblock %}

templates/btcbot/settings.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Настройки бота{% endblock %}


{% block nav_baractive_settings %}active{% endblock %}


{% block content %}
    <div class="starter-template">

        <h1 class="bold"><b>Настройки бота</b></h1>

        {% if messages %}
        <div class="alert alert-success" role="alert">
            <ul class="messages ">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

      <div class="container">
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Вкл./Выкл. объявление</th>
            <th scope="col">Целевая прибыль</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">
                {% if bot.switch_bot_sell %}
                    <form action="{% url 'btcbot:editor' %}" method="post">
                        {% csrf_token %}
                        <input type='hidden' name='bot_id' value='{{ bot.id }}' />
                        <input type='hidden' name='editor' value='switch_bot_sell_ad' />
                        <button class="btn btn-danger btn-sm" type="submit">Выключить объявление</button>
                    </form>
                {% else %}
                    <form action="{% url 'btcbot:editor' %}" method="post">
                        {% csrf_token %}
                        <input type='hidden' name='bot_id' value='{{ bot.id }}' />
                        <input type='hidden' name='editor' value='switch_bot_sell_ad' />
                        <button class="btn btn-success btn-sm" type="submit">Включить объявление</button>
                    </form>
                {% endif %}
            </th>
            <td><b>{{ bot.target_profit }}</b>
                <form action="{% url 'btcbot:editor' %}" method="post">
                    {% csrf_token %}
                    <input type='hidden' name='bot_id' value='{{ bot.id }}' />
                    <input type='hidden' name='editor' value='change_target_profit' />
                    <div class="input-group-append">
                        <input type='text' name='target_profit' value='' />
                        <button class="btn btn-info btn-sm" type="submit"><b>Сохранить</b></button>
                    </div>
                </form><br />
            </td>
          </tr>
        </tbody>
      </table>
    <br/>
  <main role="main" class="container">
    <div class="jumbotron">
        <h3>Активные кошельки для работы</h3>
        {% if wallets %}
            <p><b>{% for wallet in wallets %}{{ wallet.name }} ||| +{{ wallet.phone_number }}<br />{% endfor %}</b></p>
        {% else %}
            <p><b>Нет кошельков для работы. Свяжитесь с администратором</b></p>
        {% endif %}
    </div>
  </main>
    </div>
  </div>


{% endblock %}