autobot/urls.py
from django.contrib import admin
from django.urls import path, reverse
from django.conf.urls import include
from django.conf import settings
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='btcbot:index')),
    path('btcbot/', include('btcbot.urls')),
    path('profiles/', include('profiles.urls')),
]

admin.site.site_header = 'AutoBot Administration'

admin.site.site_header = 'LocalBitcoins_bot Administration'

btcbot/urls.py
from django.urls import path
from django.contrib.auth import views
from django.views import generic
from .views import IndexView, MessageView, SettingsView, EditorView


app_name = 'btcbot'
urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    path('messages/<pk>', MessageView.as_view(), name='message'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('editor/', EditorView.as_view(), name='editor'),
]

profiles/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import WalletsView, EditorView


app_name = 'profiles'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('wallets/', WalletsView.as_view(), name='wallets'),
    path('editor/', EditorView.as_view(), name='editor'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block meta_block_add %}{% endblock %}
    <link rel="icon" href="{% static 'images/favicon.png' %}">
    <title>{% block title %}{% endblock %}</title>    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block custom_css %}
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% endblock %}
  </head>
  <body {% block body_tag %}{% endblock %}>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% block nav_baractive_index %}{% endblock %}">
            <a class="nav-link" href="{% url 'btcbot:index' %}">Открытые сделки</a>
          </li>
          <li class="nav-item {% block nav_baractive_wallets %}{% endblock %}">
            <a class="nav-link" href="{% url 'profiles:wallets' %}" target="_blank">Кошельки</a>
          </li>
          <li class="nav-item {% block nav_baractive_settings %}{% endblock %}">
                <a class="nav-link" href="{% url 'btcbot:settings' %}">Настройки</a>
          </li>
          <li class="nav-item {% block nav_baractive_admin %}{% endblock %}">
                <a class="nav-link" href="{% url 'admin:index' %}" target="_blank">Админка</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'btcbot:index' %}">Пользователь: {{ user.get_username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profiles:logout' %}">Выйти</a>
          </li>          
          {% else %}
          <li class="nav-item {% block nav_baractive_login %}{% endblock %}">
		  <a class="nav-link" href="{% url 'profiles:login'%}?next={% url 'btcbot:index' %}">Залогиниться</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <main role="main" class="container-fluid">
        {% block content %}{% endblock %}
    </main>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
  </body>
</html>